### ISSUE TITLE
"Confirm" button for google sheets code always greyed out.

### ISSUE THREAD

**Issue by cbradburne** [YCSRobotics/GrizzlyTime#11]
**Describe the bug**
"Confirm" button always greyed out when trying to enter google sheet code.

**To Reproduce**
On, Windows 10, MacOS 10.15.7, Raspberry Pi Rasbian (full version). First time running the app the pop-up appears where I can enter the code but the "Confirm" button is always greyed out on all OSes. Fortunately the config.json file is created so I can enter the code there.

**Expected behavior**
Button should become available to press.

**Log File**
No file

**Desktop (please complete the following information):**
 - Version 2.3.0

**Comment by Daltz333** [comment]
You need to paste the full spreadsheet url, not just the ID

**Comment by cbradburne** [comment]
ah. My fault!
