### ISSUE TITLE
Spreadsheet ID Form Confirm Button Grayed Out

### ISSUE THREAD

**Issue by memtech3** [YCSRobotics/GrizzlyTime#16]
**Describe the bug**
On first launch, grizzly time refuses to accept a spreadsheet ID. Additionally, no log or configuration files are generated. I tried my own spreadsheet ID and then copied the one used in the wiki to see if it was a format issue. The ID used was `1D7aEi_M_yW5XXOYiDqvRMGM5Oe_tJwv8U9IbNskk7i4`
![image](https://user-images.githubusercontent.com/20732350/147889651-7f8b4c4c-46b4-46dd-8894-a611127bb09d.png)

**Expected behavior**
Confirm button should be enabled and log and configuration files should be generated

**Log File**
N/A

**Desktop (please complete the following information):**
 - Version 2.3.0 (From releases tab)
 - Java 11
 - Ubuntu 21.10

**Comment by Daltz333** [comment]
Try the full spreadsheet URL from your browser. Looks like I forgot to update the tutorial and the text when I made the regex change

**Comment by Daltz333** [comment]
Closed in commit 380d204

**Comment by memtech3** [comment]
can you push a release for this? Is there a way that I can propose changes to the wiki?

**Comment by Daltz333** [comment]
I fixed up the wiki and am working on a release now.
