### ISSUE TITLE
Reduce the scope of google drive access

### ISSUE THREAD

**Issue by memtech3** [YCSRobotics/GrizzlyTime#19]
Could you reduce the scope of grizzlytime's google drive access to just the grizzlytime spreadsheet? I'm not incredibly excited to leave access to my entire google drive on a pi's sd card. It probably won't be a problem but I've gotta be a little security conscious. It _seems_ like the oauth scope https://www.googleapis.com/auth/drive.file from https://developers.google.com/identity/protocols/oauth2/scopes#sheets would do the trick. I'm not sure if additional work would be needed to tag a file as `created or opened with this app`, it seems that it "shouldn't be ridiculously difficult" - famous last words

**Comment by Daltz333** [comment]
I've been meaning to get around to that. I'll probably renew my development efforts this FRC season.

**Comment by Daltz333** [comment]
After some research this isn't actually possible. It's a google limitation.

Please see:
https://issuetracker.google.com/issues/36760598?pli=1
https://stackoverflow.com/questions/61876633/google-sheet-oauth-scopes-to-only-access-a-few-files
