### ISSUE TITLE
external stylesheet not working

### ISSUE THREAD

**Issue by cbradburne** [YCSRobotics/GrizzlyTime#9]
Within the same directory as the GrizzlyTime app I've created a folder "stylesheets" and inside that, I've created a file "style.css". I've copied and pasted the root.css contents into the style.css file, adjusted a few things and saved it. Then reloaded GrizzlyTime and nothing has changed.

**Comment by cbradburne** [comment]
I've found the issue by following your code changes, notably this one:
**_"File stylesheet = new File(CommonUtils.getCurrentDir() + File.separator + "styles" + File.separator + "style.css");"_**
the folder must be named "styles" and not "stylesheets" as stated in the Release page:
**_"You can use an external stylesheet ("stylesheets/style.css")"_** 
So it's just the Release notes that need editing.

**Comment by Daltz333** [comment]
I've updated the release notes. Thanks!
